# Generated by Django 5.2.14 on 2026-06-08 12:08

from django.db import migrations

def backfill_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    spending_model = apps.get_model("SpendingsApp", "Spending")
    category_model = apps.get_model("SpendingsApp", "Category")

    user = User.objects.get(username="aaron")

    spending_model.objects.filter(user__isnull=True).update(user=user)
    category_model.objects.filter(user__isnull=True).update(user=user)

def reverse_backfill_users(apps, schema_editor):
    spending_model = apps.get_model("SpendingsApp", "Spending")
    category_model = apps.get_model("SpendingsApp", "Category")

    spending_model.objects.filter(user__isnull=False).update(user=None)
    category_model.objects.filter(user__isnull=False).update(user=None)

class Migration(migrations.Migration):

    dependencies = [
        ('SpendingsApp', '0002_category_user_spending_user'),
    ]

    operations = [
        migrations.RunPython(backfill_users, reverse_backfill_users),
    ]
